# Etapa de build: usa uma imagem Node.js para instalar dependências e construir o projeto
FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa de produção: usa uma imagem Node.js leve para rodar a aplicação
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
# Copia os arquivos necessários da etapa de build
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
# Copie a pasta public se ela existir no seu projeto
COPY --from=builder /app/public ./public
# Expõe a porta padrão do Next.js
EXPOSE 3000
# Comando para iniciar a aplicação
CMD ["npm", "start"]