services:
  frontend:
    image: my-nextjs-app:latest
    build:
      context: ./frontend/my-app
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/my-app:/app
    environment:
      - NODE_ENV=production
